BoodschappenApp/Controllers/BoodschapController.cs
using IngredientDB;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BoodschappenApp.Controllers
{
    public class BoodschapController : Controller
    {

        private DBingredient db = new DBingredient();
        // GET: Boodschap
        public ActionResult Index()
        {
            return View(db.BoodschapIngredients.ToList());
        }

        // GET: Ingredients/Create
        public ActionResult Toevoegen()
        {
            return View(db.Ingredients.ToList());
        }

     
        public ActionResult AddInventory(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            BoodschapIngredient boodschapIngredient = new BoodschapIngredient();

            boodschapIngredient.ingredient = db.Ingredients.Find(id);

            ViewBag.IngredientID = id;

            return View(boodschapIngredient);

        }

        // POST: Ingredients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
       

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddInventory([Bind(Include = "BoodschapingredientID,ingredient,Hoeveelheid,Eenheid")] BoodschapIngredient boodschapIngredient)
        {
            if (ModelState.IsValid)
            {
                Ingredient ig = db.Ingredients.Find(boodschapIngredient.ingredient.ingredientID);
                boodschapIngredient.ingredient = ig;
                db.BoodschapIngredients.Add(boodschapIngredient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(boodschapIngredient);
        }


        // GET: Ingredients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoodschapIngredient boodschapIngredient = db.BoodschapIngredients.Find(id);
            if (boodschapIngredient == null)
            {
                return HttpNotFound();
            }
            return View(boodschapIngredient);
        }

        // POST: Ingredients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BoodschapIngredientID,Ingredient,Hoeveelheid,Eenheid")] BoodschapIngredient boodschapIngredient)
        {
            if (ModelState.IsValid)
            {
                Ingredient ig = db.Ingredients.Find(boodschapIngredient.ingredient.ingredientID);
                boodschapIngredient.ingredient = ig;
                db.Entry(boodschapIngredient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(boodschapIngredient);
        }

        // GET: Ingredients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BoodschapIngredient ingredient = db.BoodschapIngredients.Find(id);
            if (ingredient == null)
            {
                return HttpNotFound();
            }
            return View(ingredient);
        }

        // POST: Ingredients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BoodschapIngredient ingredient = db.BoodschapIngredients.Find(id);
            db.BoodschapIngredients.Remove(ingredient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Gekocht(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            BoodschapIngredient boodschapIngredient = db.BoodschapIngredients.Find(id);
            if (boodschapIngredient == null)
            {
                return HttpNotFound();
            }

            InventoryIngredient inventoryIngredient = new InventoryIngredient();
            inventoryIngredient.ingredient = boodschapIngredient.ingredient;
            inventoryIngredient.Hoeveelheid = boodschapIngredient.Hoeveelheid;
            inventoryIngredient.Eenheid = boodschapIngredient.Eenheid;

            db.InventoryIngredients.Add(inventoryIngredient);
            db.BoodschapIngredients.Remove(boodschapIngredient);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

BoodschappenApp/Controllers/IngredientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IngredientDB;

namespace BoodschappenApp.Controllers
{
    public class IngredientsController : Controller
    {
        private DBingredient db = new DBingredient();

        // GET: Ingredients
        public ActionResult Index()
        {
            return View(db.Ingredients.ToList());
        }

        // GET: Ingredients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingredient ingredient = db.Ingredients.Find(id);
            if (ingredient == null)
            {
                return HttpNotFound();
            }
            return View(ingredient);
        }

        // GET: Ingredients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ingredients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ingredientID,name,merk")] Ingredient ingredient)
        {
            if (ModelState.IsValid)
            {
                db.Ingredients.Add(ingredient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ingredient);
        }

        // GET: Ingredients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingredient ingredient = db.Ingredients.Find(id);
            if (ingredient == null)
            {
                return HttpNotFound();
            }
            return View(ingredient);
        }

        // POST: Ingredients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ingredientID,name,merk")] Ingredient ingredient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ingredient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ingredient);
        }

        // GET: Ingredients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingredient ingredient = db.Ingredients.Find(id);
            if (ingredient == null)
            {
                return HttpNotFound();
            }
            return View(ingredient);
        }

        // POST: Ingredients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ingredient ingredient = db.Ingredients.Find(id);
            db.Ingredients.Remove(ingredient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BoodschappenApp/Views/Boodschap/AddInventory.cshtml
@model IngredientDB.BoodschapIngredient
@ViewBag.IngredientID

@{
    ViewBag.Title = "AddInventory";
}

<h2>AddInventory</h2>
@*@{Model.ingredient.ingredientID = ViewBag.IngredientID;}*@

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ingredient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ingredient.ingredientID, new { htmlAttributes = new { @class = "form-control" } })



        <div class="form-group">
            @Html.LabelFor(model => model.ingredient.ingredientID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ingredient.ingredientID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.ingredient.name, new { htmlAttributes = new { @class = "form-control" } })
                @Model.ingredient.name
                @Html.ValidationMessageFor(model => model.ingredient.ingredientID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ingredient.merk, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ingredient.merk, new { htmlAttributes = new { @class = "form-control" } })
                @Model.ingredient.merk
                @Html.ValidationMessageFor(model => model.ingredient.merk, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hoeveelheid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hoeveelheid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hoeveelheid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Eenheid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Eenheid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Eenheid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Voeg toe" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BoodschappenApp/Views/Boodschap/Delete.cshtml
@model IngredientDB.BoodschapIngredient
@{
    ViewBag.Title = "Delete";
}

<h2>Weet je zeker dat je dit wil verwijderen?</h2>

<table class="table-bordered">
    <tr>
        <td>@Html.DisplayNameFor(model => model.ingredient.name)</td>
        <td>@Html.DisplayFor(model => model.ingredient.name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.ingredient.merk)</td>
        <td>@Html.DisplayFor(model => model.ingredient.merk)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Hoeveelheid)</td>
        <td>@Html.DisplayFor(model => model.Hoeveelheid)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(model => model.Eenheid)</td>
        <td>@Html.DisplayFor(model => model.Eenheid)</td>
    </tr>
</table>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <p>

        <button type="submit" value="Delete" class="btn btn-default">delete</button>
        @Html.ActionLink("Back to List", "Index")
    </p>
}

BoodschappenApp/Views/Boodschap/Edit.cshtml
@model IngredientDB.BoodschapIngredient

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>boodschapIngredient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BoodschapIngredientID)

        @*<div class="form-group">
                @Html.LabelFor(model => model.Naam, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Naam, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Naam, "", new { @class = "text-danger" })
                </div>
            </div>*@


        <div class="form-group">
            @Html.LabelFor(model => model.Hoeveelheid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hoeveelheid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.ingredient.ingredientID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.ingredient.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.ingredient.merk, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hoeveelheid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Eenheid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Eenheid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Eenheid, "", new { @class = "text-danger" })
            </div>
        </div>


        <button type="submit" value="Save" class="btn btn-default">Opslaan</button>


    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BoodschappenApp/Views/Boodschap/Index.cshtml
@model IEnumerable<IngredientDB.BoodschapIngredient>

@{
    ViewBag.Title = "Index";
}

<h2>BoodschappenLijst</h2>

<p>
    @Html.ActionLink("Voeg toe", "Toevoegen")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ingredient.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ingredient.merk)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hoeveelheid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Eenheid)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.ingredient.name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ingredient.merk)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Hoeveelheid)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Eenheid)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.BoodschapIngredientID }) |
            @Html.ActionLink("Gekocht", "Gekocht", new { id = item.BoodschapIngredientID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.BoodschapIngredientID })
    </td>
</tr>
    }

</table>

BoodschappenApp/Views/Boodschap/Toevoegen.cshtml
@model IEnumerable<IngredientDB.Ingredient>
@{
    ViewBag.Title = "Toevoegen";
}

<h2>Toevoegen</h2>


<p>
    @Html.ActionLink("Create New", "Create", "Ingredients", null, null)

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.merk)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.merk)
            </td>
            <td>
                @Html.ActionLink("Voeg toe", "AddInventory", new { id = item.ingredientID })

            </td>
        </tr>
    }

</table>